/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const $confirm: typeof import('./global/global')['$confirm']
  const $error: typeof import('./global/global')['$error']
  const $info: typeof import('./global/global')['$info']
  const $message: typeof import('./global/global')['$message']
  const $notification: typeof import('./global/global')['$notification']
  const $success: typeof import('./global/global')['$success']
  const $warning: typeof import('./global/global')['$warning']
  const appStore: typeof import('./global/global')['appStore']
  const jpomWindow: typeof import('./global/global')['jpomWindow']
  const route: typeof import('./global/global')['route']
  const router: typeof import('./global/global')['router']
  const userStore: typeof import('./global/global')['userStore']
}
