--
-- The MIT License (MIT)
--
-- Copyright (c) 2019 Code Technology Studio
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy of
-- this software and associated documentation files (the "Software"), to deal in
-- the Software without restriction, including without limitation the rights to
-- use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
-- the Software, and to permit persons to whom the Software is furnished to do so,
-- subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in all
-- copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
-- FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
-- COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
-- IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
-- CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
--

-- @author bwcx_jzy


ALTER TABLE USEROPERATELOGV1
    ADD IF NOT EXISTS workspaceId VARCHAR(50) comment '所属工作空间';
ALTER TABLE USEROPERATELOGV1
    ADD IF NOT EXISTS id VARCHAR(50) not null default '' comment 'id';

update USEROPERATELOGV1
set USEROPERATELOGV1.id =USEROPERATELOGV1.REQID
where USEROPERATELOGV1.id = '';

ALTER TABLE USEROPERATELOGV1
    ADD IF NOT EXISTS createTimeMillis BIGINT COMMENT '数据创建时间';
ALTER TABLE USEROPERATELOGV1
    ADD IF NOT EXISTS modifyTimeMillis BIGINT COMMENT '数据修改时间';
ALTER TABLE USEROPERATELOGV1
    ADD IF NOT EXISTS modifyUser VARCHAR(50) comment '操作人';
ALTER TABLE USEROPERATELOGV1
    ADD IF NOT EXISTS classFeature VARCHAR(100) comment '操作的功能';
ALTER TABLE USEROPERATELOGV1
    ADD IF NOT EXISTS methodFeature VARCHAR(100) comment '操作的方法';
ALTER TABLE USEROPERATELOGV1
    ADD IF NOT EXISTS reqTime BIGINT comment '请求时间';
ALTER TABLE USEROPERATELOGV1
	ALTER COLUMN nodeId VARCHAR(50) COMMENT '节点ID';

ALTER TABLE USEROPERATELOGV1
    ALTER COLUMN dataId VARCHAR(200) COMMENT '操作的数据ID';

ALTER TABLE MONITORNOTIFYLOG
	ALTER COLUMN nodeId VARCHAR(50) COMMENT '节点ID';

ALTER TABLE MONITORNOTIFYLOG
    ADD IF NOT EXISTS workspaceId VARCHAR(50) comment '所属工作空间';
ALTER TABLE MONITORNOTIFYLOG
    ADD IF NOT EXISTS id VARCHAR(50) not null default '' comment 'id';

ALTER TABLE MONITORNOTIFYLOG
    ADD IF NOT EXISTS createTimeMillis BIGINT COMMENT '数据创建时间';
ALTER TABLE MONITORNOTIFYLOG
    ADD IF NOT EXISTS modifyTimeMillis BIGINT COMMENT '数据修改时间';


ALTER TABLE OUTGIVINGLOG
    ADD IF NOT EXISTS workspaceId VARCHAR(50) comment '所属工作空间';
ALTER TABLE OUTGIVINGLOG
    ADD IF NOT EXISTS createTimeMillis BIGINT COMMENT '数据创建时间';
ALTER TABLE OUTGIVINGLOG
    ADD IF NOT EXISTS modifyTimeMillis BIGINT COMMENT '数据修改时间';
ALTER TABLE OUTGIVINGLOG
	ADD IF NOT EXISTS modifyUser VARCHAR(50) comment '操作人';

ALTER TABLE SSHTERMINALEXECUTELOG
	ADD IF NOT EXISTS modifyUser VARCHAR(50) comment '操作人';


ALTER TABLE BUILDHISTORYLOG
    ADD IF NOT EXISTS clearOld TINYINT COMMENT '是否清空发布';
ALTER TABLE BUILDHISTORYLOG
    ADD IF NOT EXISTS name VARCHAR(100) COMMENT '构建名称';
ALTER TABLE BUILDHISTORYLOG
    ADD IF NOT EXISTS releaseCommand CLOB COMMENT '发布命令';
ALTER TABLE BUILDHISTORYLOG
    ADD IF NOT EXISTS releasePath VARCHAR(100) COMMENT '发布到的目录';
ALTER TABLE BUILDHISTORYLOG
    ALTER COLUMN releaseCommand CLOB COMMENT '发布命令';

-- @author jzy
ALTER TABLE BUILDHISTORYLOG
    ADD IF NOT EXISTS buildName VARCHAR(100) COMMENT '构建名称';
ALTER TABLE BUILDHISTORYLOG
    ADD IF NOT EXISTS createTimeMillis BIGINT COMMENT '数据创建时间';
ALTER TABLE BUILDHISTORYLOG
    ADD IF NOT EXISTS modifyTimeMillis BIGINT COMMENT '数据修改时间';
ALTER TABLE BUILDHISTORYLOG
    ADD IF NOT EXISTS modifyUser VARCHAR(50) comment '操作人';
ALTER TABLE BUILDHISTORYLOG
	ADD IF NOT EXISTS triggerBuildType int DEFAULT 0 comment '触发类型{0，手动，1 触发器,2 自动触发}';
ALTER TABLE BUILDHISTORYLOG
    ADD IF NOT EXISTS workspaceId VARCHAR(50) comment '所属工作空间';

ALTER TABLE BUILDHISTORYLOG
	ADD IF NOT EXISTS diffSync TINYINT COMMENT '增量同步';


ALTER TABLE SSHTERMINALEXECUTELOG
	ALTER COLUMN commands CLOB comment '操作的命令';

-- @author jzy 添加基础字段
ALTER TABLE SSHTERMINALEXECUTELOG
    ADD IF NOT EXISTS createTimeMillis BIGINT COMMENT '数据创建时间';
ALTER TABLE SSHTERMINALEXECUTELOG
    ADD IF NOT EXISTS modifyTimeMillis BIGINT COMMENT '数据修改时间';

-- @author bwcx_jzy
ALTER TABLE SSHTERMINALEXECUTELOG
    ADD IF NOT EXISTS workspaceId VARCHAR(50) comment '所属工作空间';

ALTER TABLE SYSTEMMONITORLOG
	ADD IF NOT EXISTS networkTime int COMMENT '延迟时间ms';

ALTER TABLE BUILDHISTORYLOG
	ADD IF NOT EXISTS buildRemark VARCHAR(255) comment '构建备注';

ALTER TABLE BUILDHISTORYLOG
	ADD IF NOT EXISTS extraData CLOB comment '额外信息，JSON 字符串格式';
