/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    CodeEditor: typeof import('./../components/codeEditor/index.vue')['default']
    CompositionTransfer: typeof import('./../components/compositionTransfer/composition-transfer.vue')['default']
    CustomSelect: typeof import('./../components/customSelect/index.vue')['default']
    LogView: typeof import('./../components/logView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolutionOutlined: typeof import('@ant-design/icons-vue')['SolutionOutlined']
    Terminal: typeof import('./../components/terminal/index.vue')['default']
    Upgrade: typeof import('./../components/upgrade/index.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    ViewPre: typeof import('./../components/logView/view-pre.vue')['default']
  }
}
